version: "3.8"

services:
  db:
    container_name: employee-db
    image:  postgres:14.8
    restart: always 
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: employees

  bk:
    build: ./employee-bk
    container_name: employee-bk-c
    ports:
      - '4200:4200'
    depends_on:
      - db
    command: npm run start:dev
    environment:
      DATABASE_URL: postgres://root:pass123@db:5432/employees
    volumes:
      - ./employee-bk:/app

  ft:
    build: ./employee-ft
    environment:
      WATCHPACK_POLLING : "true"
    container_name: employee-ft-c
    ports:
      - '6200:3000'
    stdin_open: true
    tty: true
  
    
